apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-team-quota
  namespace: dev-t
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: 1Gi
    limits.cpu: "1"
    limits.memory: 2Gi
    pods: "1"
    services: "1"

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: qa-team-quota
  namespace: qa-t
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: 1Gi
    limits.cpu: "1"
    limits.memory: 2Gi
    pods: "1"
    services: "1"

